database: /Users/lvasq/repositories/personal/codingup-evaluator/evaluator/resources/database/default.db
language: en
logotype: /Users/lvasq/repositories/personal/codingup-evaluator/evaluator/resources/logotypes/softserve
