database: /Users/lvasq/repositories/personal/codingup-evaluator/evaluator/resources/resources/database/luis2.db
language: en
logotype: /Users/lvasq/repositories/personal/codingup-evaluator/evaluator/resources/logotypes/teck
