database: /Users/lvasq/repositories/personal/codingup-evaluator/evaluator/resources/resources/database/luis.db
language: es
logotype: /Users/lvasq/repositories/personal/codingup-evaluator/evaluator/resources/logotypes/softserve
